spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/ginga_auth_db
    username: root
    password: ''
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: Z2luZ2EtcGMtYXV0aC1zZXJ2aWNlLWNsYXZlLXNlZ3VyYS0yMDI2LWp3dA==
  expiration: 86400000