spring:
  application:
    name: compatibilidad-service
  datasource:
    url: jdbc:mysql://localhost:3306/ginga_compatibilidad_db
    username: root
    password: ''
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8089

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/